project:
  type: book

book:
  title: "R/Pythonによる比較・因果推論・予測研究 (ver 0.12)"
  author: "川田恵介"
  date: "3/14/2023"
  chapters:
    - index.qmd
    - introConcept.qmd
    - introR.qmd
    - ols4blp.qmd
    - ParameterEstimation.qmd
    - Prediction.qmd
    - CausalMachineLearning.qmd
    - HeteroDiscover.qmd
    - summary.qmd
    - PreProcess.qmd
    - references.qmd

execute:
  freeze: auto
  message: false
  warning: false

bibliography: references.bib

format:
  html:
    theme: cosmo



