# 付録: 記述統計 {#sec-Description}

-   関心のあるグループ $(D)$ ごとに記述統計をまとめる

-   [Section -@sec-Table] 記述統計表を作成

-   [Section -@sec-Figure] 変数の分布がバランスしているかどうか、図示する

## 設定

::: {.panel-tabset}

### R

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(gtsummary) # 記述統計
library(cobalt) # バランス確認

Data_R <- read_csv("ExampleData/Example.csv")
```

-   [gtsummary](https://www.danieldsjoberg.com/gtsummary/) : 記述統計表作成

-   [cobalt](https://ngreifer.github.io/cobalt/) : 図作成

### Python

```{python}
import pandas as pd

Data_Python = pd.read_csv('ExampleData/Example.csv')
```

:::

## 記述統計表 {#sec-Table}

-   $D=Reform$ ごとに以下を表示


::: {.panel-tabset}

### R

-   連続変数については、 "中央値(下位25%, 上位25%)"

-   カテゴリー変数について、 "サンプルサイズ(割合)"


```{r}
Data_R |> 
  tbl_summary(by = "Reform")
```

### Python

```{python}
Data_Python.groupby('Reform').describe().T
```


:::

## バランス確認 {#sec-Figure}

-   異なるDグループ間で、Xの分布の違いを確認

-   Xの平均差/Xの標準偏差を報告 (@imbens2015 などで推奨)

```{r}
bal.tab(Reform ~ Size + BuildYear + Distance + TradeQ,
        Data_R,
        binary = "std", continuous = "std") |> 
  plot()
```

- 築年が古い、広い、駅からの距離が長い物件が、改装されがち
